## @param configInline [object] Specifies Contour's configuration directly in YAML format
## When configInline is used, Helm manages Contour's configuration ConfigMap as
## part of the release, and existingConfigMap is ignored.
## Refer to https://projectcontour.io/docs/latest/configuration for available options.
##
configInline:
  disablePermitInsecure: false
  tls:
    fallback-certificate: {}
  accesslog-format: envoy

envoy:
  service:
    type: LoadBalancer
    annotations:
      load-balancer.hetzner.cloud/network-zone: eu-central

extraDeploy:
  - apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: letsencrypt-prod-contour
    spec:
      acme:
        email: banane@alleaffengaffen.ch
        server: "https://acme-v02.api.letsencrypt.org/directory"
        privateKeySecretRef:
          name: letsencrypt-prod-contour
        solvers:
          - http01:
              ingress:
                class: contour
  - apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: letsencrypt-staging-contour
    spec:
      acme:
        email: banane@alleaffengaffen.ch
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
          name: letsencrypt-staging-contour
        solvers:
          - http01:
              ingress:
                class: contour
